### ISSUE TITLE
Status constantly set to "Idle"

### ISSUE THREAD

**Issue by CrumpThePenguin** [An0n3m0us/DiscordRPBlender#1]
On Windows. The status in Discord is constantly shown as "Idle" regardless of what I'm doing. Ensured I had discord unfocused in a different window with Blender focused so that it doesn't just switch to idle when I tab out :p 

Also unsure if this is a separate issue or could be related, but the terminal that opens as a result of my .bat to run the script gets spammed with " 'xdotool' is not recognized as an internal or external command, operable program or batch file".

**Comment by An0n3m0us** [comment]
Firstly, thanks for spending the time to submit a detailed explanation : )
I'll be looking into this soon.

Which Blender version are you using, and what Windows version?

**Comment by An0n3m0us** [comment]
I've fixed both issues; the constant running of `xdotool` and the idle status issue.

Could you try it again?

**Comment by CrumpThePenguin** [comment]
Thanks for replying so quickly!! I saw your reply yesterday before the edit so I didn't see you asking about Blender/Windows version. Blender version is 2.82 and Windows is 1909.

After downloading the updated file it seems the xdotool spam has ceased, but now it seems Discord isn't detecting Blender as being open at all. I thought it was working at first but I'm pretty sure it was just because I still had Blender set as a custom game from before I found this project. After deleting that and restarting Discord still doesn't detect anything.

Here's a screenshot of my terminal: 
![image](https://user-images.githubusercontent.com/24972809/82733697-39388e00-9cdb-11ea-993c-ceadde3e15e2.png)

**Comment by An0n3m0us** [comment]
Hmm, I'll check from my side; I'm on Linux, so things work differently : )
EDIT: It's working fine here.

**Comment by An0n3m0us** [comment]
Did you make sure to re-add your client ID on line 28?

**Comment by CrumpThePenguin** [comment]
Oops that would be it haha. After re-adding the client ID it's being
detected now but still shows me as idling. xdotool spam is still gone
though!

**Comment by An0n3m0us** [comment]
Ah, I found the issue. It should work now.

**Comment by CrumpThePenguin** [comment]
It does work now!! Super cool! Thanks for helping :)

**Comment by An0n3m0us** [comment]
No problem!

Just to clarify; `xdotool` is the Linux command I used to check if the window is active, but I forgot to make a check if the user was on Linux :P

Anyway, I'm glad it's fixed now! Thanks again!

**Comment by An0n3m0us** [comment]
Oh, if you know of any commands on Windows I can use to check the active window, please let me know; I can then implement idling in my project for Windows too.
Currently, idling is only detected on Linux.
